### ISSUE TITLE
How can I run it as a JAVA File ? 

### ISSUE THREAD

**Issue by SutirthaBoss** [emilianobonassi/jpbc#1]
Can you please show me how to run the jpbc  BLS01.java file?
I don't have idea about maven .. how to do can u help me  ...

**Comment by SutirthaBoss** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/11247500/16329852/d04b836e-3a02-11e6-9f4b-6a950093d0e3.png)

**Comment by emilianobonassi** [comment]
It cannot load the file containing the curve definition, you should be sure that your program has access to these files `https://github.com/emilianobonassi/jpbc/tree/master/params/curves` and that init correctly the pairing factory.

I suggest you to follow this example http://gas.dia.unisa.it/projects/jpbc/schemes/ss_bls01.html

**Comment by SutirthaBoss** [comment]
okkk
